apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-pod
  template:
    metadata:
      name: result-pod
      labels:
        app: voting-app-v2
        name: result-pod
    spec:
      containers:
        - name: result-pod
          image: docker/example-voting-app-result
          ports:
            - containerPort: 80
