apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-pod
  template:
    metadata:
      name: voting-pod
      labels:
        app: voting-app-v2
        name: voting-pod
    spec:
      containers:
        - name: voting-vote
          image: docker/example-voting-app-vote
          ports:
            - containerPort: 80
