apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: voting-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
  template:
    metadata:
      name: worker-pod
      labels:
        app: voting-app-v2
        name: worker-pod
    spec:
      containers:
        - name: worker-pod
          image: docker/example-voting-app-worker
