apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: voting-app-v2
    name: result-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: result-pod
