apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app-v1
    name: voting-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: voting-pod
